---

image: ${CI_REGISTRY}/docker/python-build:latest

variables:
  TWINE_USERNAME: $CI_REGISTRY_USER
  TWINE_PASSWORD: $CI_JOB_TOKEN
  TWINE_REPOSITORY_URL: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi

stages:
  - test
  - build
  - release
  - publish

test:pylint:
  stage: test
  script:
    - SCORE=$(
        pylint --exit-zero -f parseable src/ |
          awk '/Your code has been rated at/ {gsub("/.*","", $7); print $7}'
      )
    - pylint --exit-zero -f pylint_gitlab.GitlabCodeClimateReporter src/ > codequality.json
    - anybadge 
        --overwrite
        --label ${CI_JOB_NAME##*:}
        --value=${SCORE}
        --file ${CI_JOB_NAME##*:}.svg
        4=red 6=orange 8=yellow 10=green
  artifacts:
    paths: ['*.svg']
    reports:
      codequality: codequality.json

build:
  stage: build
  script:
    - python setup.py sdist bdist_wheel

  artifacts:
    paths: ['dist/*']

release:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG
  script: ['echo running release']

  release:
    name: 'Release $CI_COMMIT_TAG'
    description: ./CHANGELOG.md
    tag_name: '$CI_COMMIT_TAG'
    ref: '$CI_COMMIT_TAG'

publish:
  stage: publish
  rules:
    - if: $CI_COMMIT_TAG

  script:
    - twine upload dist/*
